markdown: rdiscount
permalink: /:title/
url: http://techstan.me
name: techstan
author: techstan
qq: 858300968
email: techstan@126.com
weibo: techstan
github: techstan
pygments: true
safe: true
paginate: 10
about: "这里是 techstan 的个人博客"
