markdown: rdiscount
highlighter: pygments
permalink: /:title/
motto: 做有意义的事儿
url: http://techstan.me
name: techstan
author: techstan
qq: 858300968
email: techstan@126.com 
duoshuo: techstan
weibo: techstan
github: techstan
pygments: true
safe: true
paginate: 10
about: "做你热爱的事，一切都会自然而然的发生"
github_username:  techstan
